### ISSUE TITLE
Administrator Portal Backend

### ISSUE THREAD

**Issue by shubham1172** [VITCMUN/munverse#3]
## To-do

You need to create a portal for admins to login and manage details related to the event. The admins have powers as listed below and they can make changes to the event as per the above points. This portal will use the authentication module which authenticates administrators to log into the admin portal. Admins are supposed to set the council name and banner when the system is used for the first time.

### Checklist
- Event
    - [x] Change event name
    - [x] Change event logo
- Council
    - [x] Change council name
    - [x] Change council banner
- Users
    - [x] Add/remove users
    - [x] Change username, password and profile picture

### Files to play with:
* tests/unit/admin - Write all test cases inside this
* controllers/admin.controller.js - Business logic
* models/user.model.js - User model
* models/council.model.js - Council model
* models/event.model.js - Event model
* routes/admin.router.js - Endpoints
* app.js - Register the admin router

**Comment by the-lost-explorer** [comment]
@shan1322 will write test scripts.
