### ISSUE TITLE
Messaging Backend

### ISSUE THREAD

**Issue by the-lost-explorer** [VITCMUN/munverse#4]
## To-do
You need to design a system which will send and receive messages by establishing an appropriate socket connection between users. Whenever someone sends a message, the message gets sent to the receiver and also to the database. If the receiver happens to be offline, the message will be sent only to the database. Whenever an offline user comes back online, the load message endpoint will be called which will load all the messages sent to that user when he/she was offline.

## Checklist
-   Send message
     -  [ ]   Direct message or via EB
     -  [ ]   Store message in the database
-   Load Message
    - [ ]   Load messages from the database for a particular user.

### Files to play with:
-   tests/unit/messages/ - Write all test cases inside this
-   models/message.model.js - Create the message model
-   controllers/message.controller.js - Message logic
-   routes/message.router.js - Endpoints
-   app.js - Register the message router
